# Generated by Django 5.0.3 on 2024-04-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_category_subscription_postcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='postCategory',
            new_name='category',
        ),
    ]
